MapСправочникОрганизации:
Mapping LOAD
    [Ссылка],
    [(არ გამოიყენება)];
LOAD
    *
FROM [lib://$(vSpace):DataFiles/Elvare_$(vPrefix)_СправочникОрганизации.qvd]
(qvd);

MapПеречислениеТипыСчетов:
Mapping LOAD
    [Ссылка],
    Value;
LOAD
    *
FROM [lib://$(vSpace):DataFiles/Elvare_$(vPrefix)_ПеречислениеТипыСчетов.qvd]
(qvd);

MapСправочникВалюты:
Mapping LOAD
    [Ссылка],
    [სიმბოლური კოდი];
LOAD
    *
FROM [lib://$(vSpace):DataFiles/Elvare_$(vPrefix)_СправочникВалюты.qvd]
(qvd);