//Mapping
$(include=[lib://Elvare:DataFiles/Debitors 0001. Mapping.qvs]);

//Mapping Custom
$(include=[lib://Elvare:DataFiles/Debitors 0002. Mapping Custom.qvs]);

//Cat. Contractors
$(include=[lib://Elvare:DataFiles/Debitors 0101. Cat. Contractors.qvs]);

//Reg. Debitors
$(include=[lib://Elvare:DataFiles/Debitors 0201. Reg. Debitors.qvs]);

//Bridge
$(include=[lib://Elvare:DataFiles/Debitors 0301. Bridge.qvs]);

//Calendar
$(include=[lib://Elvare:DataFiles/Debitors 0401. Calendar.qvs]);