//Mapping
$(include=[lib://Elvare:DataFiles/Inventory 0001. Mapping.qvs]);

//Mapping Custom
$(include=[lib://Elvare:DataFiles/Inventory 0002. Mapping Custom.qvs]);

//Cat. Items
$(include=[lib://Elvare:DataFiles/Inventory 0101. Cat. Items.qvs]);

//Reg. Inventory
$(include=[lib://Elvare:DataFiles/Inventory 0201. Reg. Inventory.qvs]);

//Bridge
$(include=[lib://Elvare:DataFiles/Inventory 0301. Bridge.qvs]);

//Calendar
$(include=[lib://Elvare:DataFiles/Inventory 0401. Calendar.qvs]);